name: "Deploy Codigo Facilito"
on:
  push:
    branches: ["main"]
jobs:
  deploy-codigofacilito:
    runs-on: ubuntu-latest
    steps:
      uses: actions/checkout@v2
      run: echo "Hacemos pull del código"
      run: echo "Correr migraciones"
      run: echo "Generar binario"
      run: echo "Publicar versión"


  